// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: pb/contextdemo.proto

package contextdemo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextRequest) Reset() {
	*x = ContextRequest{}
	mi := &file_pb_contextdemo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextRequest) ProtoMessage() {}

func (x *ContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contextdemo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextRequest.ProtoReflect.Descriptor instead.
func (*ContextRequest) Descriptor() ([]byte, []int) {
	return file_pb_contextdemo_proto_rawDescGZIP(), []int{0}
}

func (x *ContextRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextResponse) Reset() {
	*x = ContextResponse{}
	mi := &file_pb_contextdemo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResponse) ProtoMessage() {}

func (x *ContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_contextdemo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResponse.ProtoReflect.Descriptor instead.
func (*ContextResponse) Descriptor() ([]byte, []int) {
	return file_pb_contextdemo_proto_rawDescGZIP(), []int{1}
}

func (x *ContextResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pb_contextdemo_proto protoreflect.FileDescriptor

const file_pb_contextdemo_proto_rawDesc = "" +
	"\n" +
	"\x14pb/contextdemo.proto\x12\vcontextdemo\"*\n" +
	"\x0eContextRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"+\n" +
	"\x0fContextResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2O\n" +
	"\aServerB\x12D\n" +
	"\aProcess\x12\x1b.contextdemo.ContextRequest\x1a\x1c.contextdemo.ContextResponse2N\n" +
	"\aServerA\x12C\n" +
	"\x06Handle\x12\x1b.contextdemo.ContextRequest\x1a\x1c.contextdemo.ContextResponseB\x0fZ\r./contextdemob\x06proto3"

var (
	file_pb_contextdemo_proto_rawDescOnce sync.Once
	file_pb_contextdemo_proto_rawDescData []byte
)

func file_pb_contextdemo_proto_rawDescGZIP() []byte {
	file_pb_contextdemo_proto_rawDescOnce.Do(func() {
		file_pb_contextdemo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_contextdemo_proto_rawDesc), len(file_pb_contextdemo_proto_rawDesc)))
	})
	return file_pb_contextdemo_proto_rawDescData
}

var file_pb_contextdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_contextdemo_proto_goTypes = []any{
	(*ContextRequest)(nil),  // 0: contextdemo.ContextRequest
	(*ContextResponse)(nil), // 1: contextdemo.ContextResponse
}
var file_pb_contextdemo_proto_depIdxs = []int32{
	0, // 0: contextdemo.ServerB.Process:input_type -> contextdemo.ContextRequest
	0, // 1: contextdemo.ServerA.Handle:input_type -> contextdemo.ContextRequest
	1, // 2: contextdemo.ServerB.Process:output_type -> contextdemo.ContextResponse
	1, // 3: contextdemo.ServerA.Handle:output_type -> contextdemo.ContextResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_contextdemo_proto_init() }
func file_pb_contextdemo_proto_init() {
	if File_pb_contextdemo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_contextdemo_proto_rawDesc), len(file_pb_contextdemo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_contextdemo_proto_goTypes,
		DependencyIndexes: file_pb_contextdemo_proto_depIdxs,
		MessageInfos:      file_pb_contextdemo_proto_msgTypes,
	}.Build()
	File_pb_contextdemo_proto = out.File
	file_pb_contextdemo_proto_goTypes = nil
	file_pb_contextdemo_proto_depIdxs = nil
}
