// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pb/contextdemo.proto

package contextdemo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServerB_Process_FullMethodName = "/contextdemo.ServerB/Process"
)

// ServerBClient is the client API for ServerB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerBClient interface {
	Process(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*ContextResponse, error)
}

type serverBClient struct {
	cc grpc.ClientConnInterface
}

func NewServerBClient(cc grpc.ClientConnInterface) ServerBClient {
	return &serverBClient{cc}
}

func (c *serverBClient) Process(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*ContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextResponse)
	err := c.cc.Invoke(ctx, ServerB_Process_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerBServer is the server API for ServerB service.
// All implementations must embed UnimplementedServerBServer
// for forward compatibility.
type ServerBServer interface {
	Process(context.Context, *ContextRequest) (*ContextResponse, error)
	mustEmbedUnimplementedServerBServer()
}

// UnimplementedServerBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerBServer struct{}

func (UnimplementedServerBServer) Process(context.Context, *ContextRequest) (*ContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedServerBServer) mustEmbedUnimplementedServerBServer() {}
func (UnimplementedServerBServer) testEmbeddedByValue()                 {}

// UnsafeServerBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerBServer will
// result in compilation errors.
type UnsafeServerBServer interface {
	mustEmbedUnimplementedServerBServer()
}

func RegisterServerBServer(s grpc.ServiceRegistrar, srv ServerBServer) {
	// If the following call pancis, it indicates UnimplementedServerBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerB_ServiceDesc, srv)
}

func _ServerB_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerBServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerB_Process_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerBServer).Process(ctx, req.(*ContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerB_ServiceDesc is the grpc.ServiceDesc for ServerB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contextdemo.ServerB",
	HandlerType: (*ServerBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _ServerB_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/contextdemo.proto",
}

const (
	ServerA_Handle_FullMethodName = "/contextdemo.ServerA/Handle"
)

// ServerAClient is the client API for ServerA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerAClient interface {
	Handle(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*ContextResponse, error)
}

type serverAClient struct {
	cc grpc.ClientConnInterface
}

func NewServerAClient(cc grpc.ClientConnInterface) ServerAClient {
	return &serverAClient{cc}
}

func (c *serverAClient) Handle(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*ContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextResponse)
	err := c.cc.Invoke(ctx, ServerA_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerAServer is the server API for ServerA service.
// All implementations must embed UnimplementedServerAServer
// for forward compatibility.
type ServerAServer interface {
	Handle(context.Context, *ContextRequest) (*ContextResponse, error)
	mustEmbedUnimplementedServerAServer()
}

// UnimplementedServerAServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServerAServer struct{}

func (UnimplementedServerAServer) Handle(context.Context, *ContextRequest) (*ContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedServerAServer) mustEmbedUnimplementedServerAServer() {}
func (UnimplementedServerAServer) testEmbeddedByValue()                 {}

// UnsafeServerAServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerAServer will
// result in compilation errors.
type UnsafeServerAServer interface {
	mustEmbedUnimplementedServerAServer()
}

func RegisterServerAServer(s grpc.ServiceRegistrar, srv ServerAServer) {
	// If the following call pancis, it indicates UnimplementedServerAServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServerA_ServiceDesc, srv)
}

func _ServerA_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerAServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServerA_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerAServer).Handle(ctx, req.(*ContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerA_ServiceDesc is the grpc.ServiceDesc for ServerA service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerA_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "contextdemo.ServerA",
	HandlerType: (*ServerAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _ServerA_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/contextdemo.proto",
}
